# Generated by Django 4.2.2 on 2023-07-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product',
            new_name='product_name',
        ),
    ]
