# Generated by Django 4.2.2 on 2023-07-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_product_variation_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_name',
            new_name='_product_name',
        ),
    ]
