# Generated by Django 4.2.2 on 2023-07-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_product_name_variation__product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='_product_name',
            new_name='product',
        ),
    ]
