# Generated by Django 4.2.2 on 2023-07-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename__product_name_variation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
