# Generated by Django 4.2.2 on 2023-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productgallary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallary',
            name='image',
            field=models.ImageField(max_length=255, upload_to='store/products'),
        ),
    ]
