# Generated by Django 4.2.2 on 2023-08-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productgallary_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGallary',
            new_name='ProductGallery',
        ),
    ]
