# Generated by Django 4.2.2 on 2023-08-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
